### ISSUE TITLE
Problem: listener didn't work in termux 

### ISSUE THREAD

**Issue by ghost** [Deadpool2000/Paybag#2]
When I start a listener.. it shows..
👇
Select operating system to create listner

1) Android
2) Windows
3) Linux

99) Back to main menu

Select your choice >> 1

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Paybag/paybag.py", line 590, in <module>
    sel()
  File "/data/data/com.termux/files/home/Paybag/paybag.py", line 524, in sel
    sel2()
  File "/data/data/com.termux/files/home/Paybag/paybag.py", line 379, in sel2
    table()
  File "/data/data/com.termux/files/home/Paybag/paybag.py", line 185, in table
    inte=os.listdir('/sys/class/net/')
PermissionError: [Errno 13] Permission denied: '/sys/class/net/'

~/Paybag $

Please help me to fix this problem..😥😢
![Screenshot_2022-08-17-09-38-13-000_com termux](https://user-images.githubusercontent.com/57536521/185032985-5362cce5-a2f0-44a6-85cf-5dbdac6b5084.jpg)

**Comment by Deadpool2000** [comment]
Okay. I will check if there is any issue. I'll update you after resolving issue.

**Comment by Brokong** [comment]
Has this been fixed? I'm getting the exact issue.

**Comment by Deadpool2000** [comment]
I'm working on this issue. Need some time :)

**Comment by ramsy0dev** [comment]
@Brokong Your phone should be rooted, or else it wouldn't work. The script is trying to list the directory "/sys/class/net" which cannot be accessed unless you have root permission and in your case i don't think so.

**Comment by Callguest** [comment]
Well how to root a ph

**Comment by ramsy0dev** [comment]
@Callguest https://giybf.com

**Comment by Typotu** [comment]
اعمل على نفس المشكلة اريد حلا فوري

**Comment by Typotu** [comment]
هل من حل

**Comment by thunderthunder8459-alt** [comment]
sh: 1: msfvenom: not found
